version: '3.8'

services:
  # Frontend Next.js app
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ML_API_URL=http://ml-api:8000
    depends_on:
      - ml-api

  # ML API service with real model
  ml-api:
    build:
      context: ./services/ml-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - MODEL_PATH=financeai_lgbm.pkl
    volumes:
      - ./services/ml-api:/app
      - ./apps/web/public/model:/app/model